default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: blog_development


test:
  <<: *default
  database: blog_test

production:
  <<: *default
  database: blog-matej_production
  username: blog-matej
  password: <%= ENV['BLOG-MATEJ_DATABASE_PASSWORD'] %>
